In [1]:
import pandas as pd

In [3]:
results = pd.read_csv('../Cleaned Data/Daily Game Result.csv')
results.head()

,Date,HomeTeam,AwayTeam,Type,Final_Score_A,Final_Score_B,Final_Points,Win_Count,Draw_Count,Loss_Count,Half_Score_A,Half_Score_B,Half_Points
0,1/1/2002,Charlton,Ipswich,Home,3,2,3,1,0,0,2,2,1
1,1/1/2002,Chelsea,Southampton,Home,2,4,0,0,0,1,2,1,3
2,1/1/2002,Leeds,West Ham,Home,3,0,3,1,0,0,2,0,3
3,1/1/2002,Liverpool,Bolton,Home,1,1,1,0,1,0,0,0,1
4,1/1/2002,Middlesbrough,Everton,Home,1,0,3,1,0,0,0,0,1

In [10]:
results

,Date,HomeTeam,AwayTeam,Type,Final_Score_A,Final_Score_B,Final_Points,Win_Count,Draw_Count,Loss_Count,Half_Score_A,Half_Score_B,Half_Points
0,13/08/11,Blackburn,Wolves,Home,1,2,0,0,0,1,1,1,1
1,13/08/11,Fulham,Aston Villa,Home,0,0,1,0,1,0,0,0,1
2,13/08/11,Liverpool,Sunderland,Home,1,1,1,0,1,0,1,0,3
3,13/08/11,Newcastle,Arsenal,Home,0,0,1,0,1,0,0,0,1
4,13/08/11,QPR,Bolton,Home,0,4,0,0,0,1,0,1,0
5,13/08/11,Wigan,Norwich,Home,1,1,1,0,1,0,1,1,1
6,14/08/11,Stoke,Chelsea,Home,0,0,1,0,1,0,0,0,1
7,14/08/11,West Brom,Man United,Home,1,2,0,0,0,1,1,1,1
8,15/08/11,Man City,Swansea,Home,4,0,3,1,0,0,0,0,1
9,20/08/11,Arsenal,Liverpool,Home,0,2,0,0,0,1,0,0,1
10,20/08/11,Aston Villa,Blackburn,Home,3,1,3,1,0,0,2,0,3
11,20/08/11,Chelsea,West Brom,Home,2,1,3,1,0,0,0,1,0
12,20/08/11,Everton,QPR,Home,0,1,0,0,0,1,0,1,0
13,20/08/11,Sunderland,Newcastle,Home,0,1,0,0,0,1,0,0,1
14,20/08/11,Swansea,Wigan,Home,0,0,1,0,1,0,0,0,1
15,21/08/11,Bolton,Man City,Home,2,3,0,0,0,1,1,2,0
16,21/08/11,Norwich,Stoke,Home,1,1,1,0,1,0,1,0,3
17,21/08/11,Wolves,Fulham,Home,2,0,3,1,0,0,2,0,3
18,22/08/11,Man United,Tottenham,Home,3,0,3,1,0,0,0,0,1
19,27/08/11,Aston Villa,Wolves,Home,0,0,1,0,1,0,0,0,1
20,27/08/11,Blackburn,Everton,Home,0,1,0,0,0,1,0,0,1
21,27/08/11,Chelsea,Norwich,Home,3,1,3,1,0,0,1,0,3
22,27/08/11,Liverpool,Bolton,Home,3,1,3,1,0,0,1,0,3
23,27/08/11,Swansea,Sunderland,Home,0,0,1,0,1,0,0,0,1
24,27/08/11,Wigan,QPR,Home,2,0,3,1,0,0,1,0,3
25,28/08/11,Man United,Arsenal,Home,8,2,3,1,0,0,3,1,3
26,28/08/11,Newcastle,Fulham,Home,2,1,3,1,0,0,0,0,1
27,28/08/11,Tottenham,Man City,Home,1,5,0,0,0,1,0,2,0
28,28/08/11,West Brom,Stoke,Home,0,1,0,0,0,1,0,0,1
29,10/9/11,Arsenal,Swansea,Home,1,0,3,1,0,0,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12130,20/04/02,Charlton,Newcastle,Away,0,3,0,0,0,1,0,1,0
12131,20/04/02,Everton,Southampton,Away,1,0,3,1,0,0,1,0,3
12132,20/04/02,Sunderland,West Ham,Away,0,3,0,0,0,1,0,1,0
12133,21/04/02,Ipswich,Arsenal,Away,0,2,0,0,0,1,0,0,1
12134,23/04/02,Newcastle,Blackburn,Away,2,2,1,0,1,0,0,1,0
12135,23/04/02,Bolton,Fulham,Away,0,3,0,0,0,1,0,1,0
12136,24/04/02,West Ham,Arsenal,Away,0,2,0,0,0,1,0,0,1
12137,24/04/02,Middlesbrough,Ipswich,Away,0,1,0,0,0,1,0,0,1
12138,27/04/02,Southampton,Aston Villa,Away,1,2,0,0,0,1,0,2,0
12139,27/04/02,Sunderland,Charlton,Away,2,2,1,0,1,0,2,1,3
12140,27/04/02,Leeds,Derby,Away,1,0,3,1,0,0,1,0,3
12141,27/04/02,Leicester,Fulham,Away,0,0,1,0,1,0,0,0,1
12142,27/04/02,Man United,Ipswich,Away,1,0,3,1,0,0,1,0,3
12143,27/04/02,Chelsea,Middlesbrough,Away,2,0,3,1,0,0,2,0,3
12144,27/04/02,West Ham,Newcastle,Away,1,3,0,0,0,1,1,1,1
12145,27/04/02,Liverpool,Tottenham,Away,0,1,0,0,0,1,0,1,0
12146,28/04/02,Blackburn,Everton,Away,2,1,3,1,0,0,1,0,3
12147,29/04/02,Arsenal,Bolton,Away,2,0,3,1,0,0,2,0,3
12148,8/5/02,Blackburn,Liverpool,Away,3,4,0,0,0,1,1,2,0
12149,8/5/02,Arsenal,Man United,Away,1,0,3,1,0,0,0,0,1
12150,11/5/02,Everton,Arsenal,Away,3,4,0,0,0,1,2,2,1
12151,11/5/02,Fulham,Blackburn,Away,0,3,0,0,0,1,0,0,1
12152,11/5/02,Aston Villa,Chelsea,Away,3,1,3,1,0,0,1,0,3
12153,11/5/02,Middlesbrough,Leeds,Away,0,1,0,0,0,1,0,0,1
12154,11/5/02,Tottenham,Leicester,Away,1,2,0,0,0,1,0,0,1
12155,11/5/02,Ipswich,Liverpool,Away,0,5,0,0,0,1,0,2,0
12156,11/5/02,Charlton,Man United,Away,0,0,1,0,1,0,0,0,1
12157,11/5/02,Newcastle,Southampton,Away,1,3,0,0,0,1,0,2,0
12158,11/5/02,Derby,Sunderland,Away,1,1,1,0,1,0,0,1,0
12159,11/5/02,Bolton,West Ham,Away,1,2,0,0,0,1,0,1,0

In [18]:
tmp = results['Date'].str.split("/")[:][2]
tmp

['13', '08', '11']

In [7]:
results.to_csv('../Cleaned Data/Daily Game Result.csv')